# Generated by Django 4.2.1 on 2023-05-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampusConnect_app', '0002_onlineclassroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
